Reconnect tracker after turn off and on
cntools/libsurvive pull request #318
Opened 2024-10-21 12:00 UTC by throni3git

When turning a watchman-connected tracker device off and on again, the global scene solver failed due to some old scenes and the `handle_transfer` function in `src/driver_vive.libusb.h` did not go to the `object_turned_off` label. More info in #314.

2026-07-13 15:12 UTC, bl4ckb0ne requested changes

2026-07-13 15:12 UTC, bl4ckb0ne commented on src/driver_vive.c
> +
The function needs a better place, I'm not fond of moving it higher so `src/driver_vive_libusb.h` can use it.

2026-07-13 15:12 UTC, bl4ckb0ne commented
Apologies for the delay in the review, I wrote the comment and forgot to submit it, it has been pending for a while.

2026-07-13 15:20 UTC, throni3git commented on src/driver_vive.c
> +
what would be a better solution?

2026-07-13 18:05 UTC, bl4ckb0ne commented on src/driver_vive.c
> +
Have the signature moved to `src/driver_vive.libusb.h`, somewhere in the beginning of the file.

2026-07-21 22:00 UTC, throni3git commented on src/driver_vive.c
> +
i explicitly did it this way to have `survive_device_is_rf` available in this file, since the function is used in line 588 and 613

moving it to only `src/driver_vive.libusb.h` would make the compilation break when using HIDAPI instead of LibUSB?!

2026-07-22 14:04 UTC, bl4ckb0ne commented on src/driver_vive.c
> +
Mh you're right. I think this is more of a structural problem regarding how all those file interacts and is out of scope for this fix. I'll handle that later.

For the moment I think this is the best we can do.

2026-07-22 14:04 UTC, bl4ckb0ne approved these changes
LGTM!

2026-07-22 14:05 UTC, merged